### ISSUE TITLE
Dark mode or custom CSS

### ISSUE THREAD

**Issue by flowerornament** [xyhp915/logseq-journals-calendar#10]
I used a dark theme with Logseq and I haven't been able to quickly find a way to make the calendar match, or at least be any color other than white.

Three options I can imagine:
1. Dark mode option built-in
2. A list of styles that can be modified made available in the docs
3. Calendar respects theme CSS variables

I don't know about the feasibility of (2) and (3).

**Comment by xyhp915** [comment]
That(1) was already supported, though not respecting theme CSS vars from the host. But (3) is in plan in next optimization :)

![2022-01-22 20 42 41](https://user-images.githubusercontent.com/1779837/150639125-7934d078-019b-494c-a06a-75739b6dd12b.gif)

**Comment by flowerornament** [comment]
Ah, indeed the calendar now displays in dark mode. I'm not sure why it didn't before. Thank you!

**Comment by shmup** [comment]
For what it's worth, out of the box:

1) using default theme
2) set to dark mode (not system default)
3) installing this from marketplace

leads to

4) click calendar icon and see the light mode calendar

But, luckily!

5) Closing and reopening worked, now it's using dark styles

**Comment by mishrasidhant** [comment]
Restarting Logseq after install seems to fix this issue
