### ISSUE TITLE
Not working anymore?

### ISSUE THREAD

**Issue by sphoenixee** [xyhp915/logseq-journals-calendar#13]
Thanks for developing what seems to be a very useful plugin. Unfortunately I cannot get it to work. I am using Logseq .7.1 on Windows (and .7.4 on a different Windows machine). I install the plugin but no calendar icon shows up in the top right. Am I doing something wrong? I seem to be able to get other plugins to work just fine. Thanks for any help you can provide.

**Comment by sphoenixee** [comment]
It seems to be working now.

**Comment by gaga5lala** [comment]
I've encountered the same issue with Logseq 0.75 and Journals calendar plugin 0.10.5. The problem fixed by disable and enable the plugin.
