### ISSUE TITLE
Wrong day highlighted

### ISSUE THREAD

**Issue by mikejones3** [xyhp915/logseq-journals-calendar#15]
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/13171497/181994385-d3a6ea2d-415f-476b-bd65-16ee7ee0ff00.png">

AS you can see in the image above its highlighting the 27th of July and it is actually the 30th of July.

**Comment by mikejones3** [comment]
A restart fixed it, but not sure how it got stuck :-)

**Comment by aalhendi** [comment]
### Steps to reproduce:
1. Open logseq
2. Wait until a day transition happens (past midnight/``00:00``)
3. Check calendar plugin

### Likely Causes:
The app sets a state variable in [App.vue L68](https://github.com/xyhp915/logseq-journals-calendar/blob/main/src/App.vue#L68) to hold the highlighted date. This date is not being updated past midnight. 

### Possible Fixes:
Check the date on calendar open by comparing the ``day`` property of the stored date with the ``day`` property of a newly generated date.

**Comment by josh-sweaney** [comment]
Came here to report this same issue. If LogSeq is left open overnight (I usually just leave it running in the background all the time) then the calendar never updates to the correct date without a restart.

**Comment by nhalstead** [comment]
Came here to report this same issue.

**Comment by xxchan** [comment]
A reload can also fix it

<img width="413" alt="image" src="https://user-images.githubusercontent.com/37948597/213825105-9dcb3e58-7422-47a6-85b0-2cb97d972578.png">
