### ISSUE TITLE
Timeout issue with plugin when logseq starts

### ISSUE THREAD

**Issue by pmaranin** [xyhp915/logseq-journals-calendar#30]
Using logseq 0.9.4 and plugin v0.10.8 on Windows 11, I'm getting the following error when logseq starts 

`This plugin #logseq-journals-calendar takes too long to load, affecting the application startup time and potentially causing other plugins to fail to load`

here is what I have in the console

![image](https://user-images.githubusercontent.com/48673891/237027950-a20e9314-03c3-4d7c-970c-23ad30ac8cf5.png)

Thanks

**Comment by soritchie** [comment]
Same happening for me. Exact setup as above.

**Comment by Vitor12xx** [comment]
I just updated to v0.10.9 and this started to happen to me as well

**Comment by Vitor12xx** [comment]
Found the error. The last commit bumped the version but left behind a dev variable. 
![image](https://github.com/xyhp915/logseq-journals-calendar/assets/33634312/434e33ec-7e2b-40fd-a988-0202b65937ab)
Delete that 'devEntry' line and it should be working,

**Comment by delucca** [comment]
Same thing here

**Comment by HatsuneMK00** [comment]
> Found the error. The last commit bumped the version but left behind a dev variable.
> ![image](https://user-images.githubusercontent.com/33634312/237128285-434e33ec-7e2b-40fd-a988-0202b65937ab.png)
> Delete that 'devEntry' line and it should be working,

This fix worked for me! Appreciate it!

**Comment by xyhp915** [comment]
My bad! Fixed in v0.10.10 Thanks to @Vitor12xx

**Comment by soritchie** [comment]
> My bad! Fixed in v0.10.10 Thanks to @Vitor12xx

Thanks!

**Comment by s373r** [comment]
@xyhp915 , fixed after updating to v0.10.10 (just tested) - thanks so much for the quick reaction!

**Comment by xyhp915** [comment]
> Fun fact: I just played with it while I was opening it, and if I switch effect to true, the problem disappears !!! (and if I switch it back to false, it comes back

@pmaranin thanks for you details.

I wonder if it could be due to caching! Try to open the `Dev tool (F12)`, then force to reload `ctrl+R` or clear caches manually.

**Comment by pmaranin** [comment]
same symptom, the reload does not make the problem disappear when logseq is started with  "effect":false
the only way for me to make the error disappear is to set  "effect" to true

What does the "effect" setting do ?

**Comment by xyhp915** [comment]
> same symptom, the reload does not make the problem disappear when logseq is started with "effect":false the only way for me to make the error disappear is to set "effect" to true
> 
> What does the "effect" setting do ?

When `effect:false` is enabled, the plugin will run in the `lsp://` isolated sandbox, and vice versa, it will be in the shared sandbox under the same domain as the host. This plugin does not have `effect` enabled by default.

![CleanShot 2023-05-11 at 09 51 54@2x](https://github.com/xyhp915/logseq-journals-calendar/assets/1779837/6d5e227f-6f01-403a-b320-89f40cbad527)

**Comment by pmaranin** [comment]
Thanks @xyhp915 for the clarification. I'm not sure I understand the consequence of the shared/isolated sandbox, but as the workaround works for me (with no negative side consequences for now), I am happy running the plugin with effect=true.
