### ISSUE TITLE
[0.4.5] Clicking on empty date wont create journal at all

### ISSUE THREAD

**Issue by guoboism** [xyhp915/logseq-journals-calendar#6]
Now with 0,4,5 when clicking on empty date, logseq display a blank page and can not edit. (No title)
I guess they change the interface to create journal or sth?

![image](https://user-images.githubusercontent.com/705499/140628507-99d5a2c7-a80f-4055-b601-5fabf241e3a8.png)

**Comment by xyhp915** [comment]
@guoboism Fixed 0.10.0
