### ISSUE TITLE
Wrong "today" mark

### ISSUE THREAD

**Issue by fredguth** [xyhp915/logseq-journals-calendar#7]
If I am not mistaken, the calendar has a special css for "today".  But it is showing the wrong date:
<img width="490" alt="Screen Shot 2021-11-18 at 15 29 12" src="https://user-images.githubusercontent.com/392879/142476311-c9dca653-d78e-44fb-a14a-7a5b23579737.png">

**Comment by xyhp915** [comment]
I can't reproduce it. But the "Today" interaction will be redesigned soon :)

**Comment by danieltomasz** [comment]
I can confirm this, today is 19.12 and  plugin shows 16.12
![image](https://user-images.githubusercontent.com/7980381/146693560-5340db2e-253c-4012-bf50-3a3f7b9cba6f.png)

**Comment by isosphere** [comment]
> I can confirm this, today is 19.12 and plugin shows 16.12 ![image](https://user-images.githubusercontent.com/7980381/146693560-5340db2e-253c-4012-bf50-3a3f7b9cba6f.png) After restarting app it show again ok date my logseq was probably not restarted since 16.12
> 
> @xyhp915 to reproduce please start the logseq a day before (or artificially change date) plugin probably will not change date next day without restart Also when I create note for next, it doesnt show dot until I restart logseq

I can confirm this be behaviour. I rarely turn my computer off and leave logseq running for days at a time. Seems the plugin doesn't update the current date after initial startup. 

Looks like we rely on `dayjs/esm/plugin/isToday` to determine the current date. 

Here's the snippet that I think controls the behaviour:
https://github.com/xyhp915/logseq-journals-calendar/blob/91766617b0b44248145a708d81eb2d58da7cf60e/src/App.vue#L95-L100

This gets executed in the `mounted` method. I'm not familiar with logseq plugins, but it sounds like this is a run-once-on-load method. To adjust this behaviour we could extract this code to a separate method, have `mounted` call that method, and have a scheduled / event-based call to the method at/after midnight somehow.

**Comment by vslinko** [comment]
I can confirm that the problem is reproducing when the logseq is running for more than one day.
